# Generated by Django 5.2 on 2025-04-05 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("message", "0001_initial"),
        ("recipient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_dispatch",
                    models.DateTimeField(help_text="yyyy-mm-dd 00:00:00", verbose_name="Дата и время первой отправки"),
                ),
                (
                    "end_dispatch",
                    models.DateTimeField(
                        help_text="yyyy-mm-dd 00:00:00", verbose_name="Дата и время окончания отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CO", "Завершена"), ("CR", "Создана"), ("LA", "Запущена")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message",
                        to="message.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="recipients", to="recipient.recipient", verbose_name="Получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status", "first_dispatch", "message"],
            },
        ),
    ]
