# Generated by Django 5.2 on 2025-04-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=50, unique=True, verbose_name="Email")),
                ("full_name", models.CharField(max_length=150, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["full_name"],
            },
        ),
    ]
